apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  replicaCount: "3"
  staleReplicaTimeout: "30"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
